<?php

declare(strict_types=1);

namespace Hengeb\Listig\Tests\Mail;

use Hengeb\Listig\Config\ListConfig;
use Hengeb\Listig\Logging\LogLevel;
use Hengeb\Listig\Logging\Logger;
use Hengeb\Listig\Mail\HeaderFilter;
use Hengeb\Listig\Mail\IncomingMailFilter;
use Hengeb\Listig\Mail\SpamFilter;
use Hengeb\Listig\RateLimit\RateLimiter;
use PhpImap\IncomingMail;
use PHPUnit\Framework\TestCase;

class IncomingMailFilterTest extends TestCase
{
    private function filter(): IncomingMailFilter
    {
        return new IncomingMailFilter(
            $this->createStub(RateLimiter::class),
            new HeaderFilter(),
            new SpamFilter([], new Logger(LogLevel::Error)),
        );
    }

    private function runFilter(string $headersRaw, string $autoSubmitted = '', string $subject = 'Hallo', string $from = 'a@example.com'): \Hengeb\Listig\Mail\FilterResult
    {
        $mail = new IncomingMail();
        $mail->headersRaw = $headersRaw;
        $mail->autoSubmitted = $autoSubmitted;
        $mail->subject = $subject;
        $mail->fromAddress = $from;
        $list = new ListConfig('mylist', 'mylist@example.org', []);
        return $this->filter()->filter($mail, $list, 'raw', []);
    }

    public function testAutoRepliedIsSilentlyDiscardedAndDeleted(): void
    {
        $result = $this->runFilter("Auto-Submitted: auto-replied\r\n", 'auto-replied', 'Automatische Antwort: x');
        $this->assertTrue($result->isDiscard);
        $this->assertTrue($result->forceDelete);
    }

    public function testPrecedenceAutoReplyIsDiscarded(): void
    {
        $result = $this->runFilter("Precedence: auto_reply\r\n");
        $this->assertTrue($result->isDiscard);
    }

    public function testAutoGeneratedIsStillABounce(): void
    {
        $this->assertTrue($this->runFilter("Auto-Submitted: auto-generated\r\n", 'auto-generated')->isBounce);
    }

    public function testMailerDaemonWithAutoResponseSuppressIsStillABounce(): void
    {
        $result = $this->runFilter("X-Auto-Response-Suppress: All\r\n", '', 'Undelivered Mail Returned to Sender', 'MAILER-DAEMON@example.com');
        $this->assertTrue($result->isBounce);
    }
}
