<?php

declare(strict_types=1);

namespace Hengeb\Listig\Tests\Mail;

use Hengeb\Listig\Config\ListConfig;
use Hengeb\Listig\Logging\LogLevel;
use Hengeb\Listig\Logging\Logger;
use Hengeb\Listig\Mail\HeaderFilter;
use Hengeb\Listig\Mail\IncomingMailFilter;
use Hengeb\Listig\Mail\ReplyTarget;
use Hengeb\Listig\Mail\ReplyTargetStore;
use Hengeb\Listig\Member\InlineMemberResolver;
use Hengeb\Listig\Member\Member;
use Hengeb\Listig\Mail\SpamFilter;
use Hengeb\Listig\RateLimit\RateLimiter;
use PhpImap\IncomingMail;
use PHPUnit\Framework\TestCase;

class IncomingMailFilterTest extends TestCase
{
    private function filter(): IncomingMailFilter
    {
        return new IncomingMailFilter(
            $this->createStub(RateLimiter::class),
            new HeaderFilter(),
            new SpamFilter([], new Logger(LogLevel::Error)),
            $this->createStub(ReplyTargetStore::class),
        );
    }

    private function runFilter(string $headersRaw, string $autoSubmitted = '', string $subject = 'Hallo', string $from = 'a@example.com'): \Hengeb\Listig\Mail\FilterResult
    {
        $mail = new IncomingMail();
        $mail->headersRaw = $headersRaw;
        $mail->autoSubmitted = $autoSubmitted;
        $mail->subject = $subject;
        $mail->fromAddress = $from;
        $list = new ListConfig('mylist', 'mylist@example.org', []);
        return $this->filter()->filter($mail, $list, 'raw', []);
    }

    public function testAutoRepliedIsSilentlyDiscardedAndDeleted(): void
    {
        $result = $this->runFilter("Auto-Submitted: auto-replied\r\n", 'auto-replied', 'Automatische Antwort: x');
        $this->assertTrue($result->isDiscard);
        $this->assertTrue($result->forceDelete);
    }

    public function testPrecedenceAutoReplyIsDiscarded(): void
    {
        $result = $this->runFilter("Precedence: auto_reply\r\n");
        $this->assertTrue($result->isDiscard);
    }

    public function testAutoGeneratedIsStillABounce(): void
    {
        $this->assertTrue($this->runFilter("Auto-Submitted: auto-generated\r\n", 'auto-generated')->isBounce);
    }

    public function testMailerDaemonWithAutoResponseSuppressIsStillABounce(): void
    {
        $result = $this->runFilter("X-Auto-Response-Suppress: All\r\n", '', 'Undelivered Mail Returned to Sender', 'MAILER-DAEMON@example.com');
        $this->assertTrue($result->isBounce);
    }

    private function runReply(array $rawConfig, string $sender, bool $targetResolves = true): \Hengeb\Listig\Mail\FilterResult
    {
        $store = $this->createStub(ReplyTargetStore::class);
        $store->method('extractToken')->willReturn('tok');
        $store->method('resolve')->willReturn($targetResolves ? new ReplyTarget(new Member('t@example.org'), true) : null);
        $filter = new IncomingMailFilter(
            $this->createStub(RateLimiter::class),
            new HeaderFilter(),
            new SpamFilter([], new Logger(LogLevel::Error)),
            $store,
        );
        $mail = new IncomingMail();
        $mail->headersRaw = "To: mylist+r-tok@example.org\r\n";
        $mail->autoSubmitted = '';
        $mail->subject = 'Re: Hallo';
        $mail->fromAddress = $sender;
        $list = new ListConfig('mylist', 'mylist@example.org', $rawConfig, new InlineMemberResolver(['m@example.org'], ['o@example.org']));
        return $filter->filter($mail, $list, 'raw', []);
    }

    public function testReplyTokenRejectedForNonMember(): void
    {
        $result = $this->runReply(['reply-to' => 'masked-sender'], 'outsider@example.com');
        $this->assertSame('reject.reply_not_allowed', $result->reason);
    }

    public function testReplyTokenOnNonMaskedListIsRejected(): void
    {
        $result = $this->runReply(['reply-to' => 'list'], 'm@example.org');
        $this->assertSame('reject.reply_not_enabled', $result->reason);
    }

    public function testReplyTokenWithUnresolvableTargetIsRejected(): void
    {
        $result = $this->runReply(['reply-to' => 'masked-sender'], 'm@example.org', false);
        $this->assertSame('reject.reply_target_unknown', $result->reason);
    }

    public function testMaskedSenderIgnoresPostAccessMembers(): void
    {
        $result = $this->runReply(['reply-to' => 'masked-sender', 'post-access-members' => 'moderate'], 'm@example.org');
        $this->assertTrue($result->isDistribute);
        $result = $this->runReply(['reply-to' => 'masked-sender', 'post-access-members' => 'deny'], 'm@example.org');
        $this->assertTrue($result->isDistribute);
    }

    public function testMaskedBothHonoursPostAccessMembers(): void
    {
        $result = $this->runReply(['reply-to' => 'masked-both', 'post-access-members' => 'deny'], 'm@example.org');
        $this->assertSame('reject.members_denied', $result->reason);
        $result = $this->runReply(['reply-to' => 'masked-both', 'post-access-members' => 'moderate'], 'm@example.org');
        $this->assertTrue($result->isModeration);
    }
}
