<?php

declare(strict_types=1);

namespace Hengeb\Listig\Tests\Mail;

use Hengeb\Listig\Config\ListConfig;
use Hengeb\Listig\Logging\LogLevel;
use Hengeb\Listig\Logging\Logger;
use Hengeb\Listig\Mail\HeaderFilter;
use Hengeb\Listig\Mail\IncomingMailFilter;
use Hengeb\Listig\Mail\ReplyTarget;
use Hengeb\Listig\Mail\ReplyTargetStore;
use Hengeb\Listig\Mail\OrganizationalDomain;
use Hengeb\Listig\Mail\ReplyThreadStore;
use Hengeb\Listig\Mail\SenderAuthenticator;
use Hengeb\Listig\Member\InlineMemberResolver;
use Hengeb\Listig\Member\Member;
use Hengeb\Listig\Mail\SpamFilter;
use Hengeb\Listig\RateLimit\RateLimiter;
use PhpImap\IncomingMail;
use PHPUnit\Framework\TestCase;

class IncomingMailFilterTest extends TestCase
{
    private function filter(): IncomingMailFilter
    {
        return new IncomingMailFilter(
            $this->createStub(RateLimiter::class),
            new HeaderFilter(),
            new SpamFilter([], new Logger(LogLevel::Error)),
            $this->createStub(ReplyTargetStore::class),
            $this->createStub(ReplyThreadStore::class),
            new SenderAuthenticator(new HeaderFilter(), new OrganizationalDomain()),
        );
    }

    private function runFilter(string $headersRaw, string $autoSubmitted = '', string $subject = 'Hallo', string $from = 'a@example.com'): \Hengeb\Listig\Mail\FilterResult
    {
        $mail = new IncomingMail();
        $mail->headersRaw = $headersRaw;
        $mail->autoSubmitted = $autoSubmitted;
        $mail->subject = $subject;
        $mail->fromAddress = $from;
        $list = new ListConfig('mylist', 'mylist@example.org', []);
        return $this->filter()->filter($mail, $list, 'raw', []);
    }

    public function testAutoRepliedIsSilentlyDiscardedAndDeleted(): void
    {
        $result = $this->runFilter("Auto-Submitted: auto-replied\r\n", 'auto-replied', 'Automatische Antwort: x');
        $this->assertTrue($result->isDiscard);
        $this->assertTrue($result->forceDelete);
    }

    public function testPrecedenceAutoReplyIsDiscarded(): void
    {
        $result = $this->runFilter("Precedence: auto_reply\r\n");
        $this->assertTrue($result->isDiscard);
    }

    public function testAutoGeneratedIsStillABounce(): void
    {
        $this->assertTrue($this->runFilter("Auto-Submitted: auto-generated\r\n", 'auto-generated')->isBounce);
    }

    public function testMailerDaemonWithAutoResponseSuppressIsStillABounce(): void
    {
        $result = $this->runFilter("X-Auto-Response-Suppress: All\r\n", '', 'Undelivered Mail Returned to Sender', 'MAILER-DAEMON@example.com');
        $this->assertTrue($result->isBounce);
    }

    private function runReply(array $rawConfig, string $sender, bool $targetResolves = true): \Hengeb\Listig\Mail\FilterResult
    {
        $store = $this->createStub(ReplyTargetStore::class);
        $store->method('extractToken')->willReturn('tok');
        $store->method('resolve')->willReturn($targetResolves ? new ReplyTarget(new Member('t@example.org'), true) : null);
        $filter = new IncomingMailFilter(
            $this->createStub(RateLimiter::class),
            new HeaderFilter(),
            new SpamFilter([], new Logger(LogLevel::Error)),
            $store,
            $this->createStub(ReplyThreadStore::class),
            new SenderAuthenticator(new HeaderFilter(), new OrganizationalDomain()),
        );
        $mail = new IncomingMail();
        $mail->headersRaw = "To: mylist+r-tok@example.org\r\n";
        $mail->autoSubmitted = '';
        $mail->subject = 'Re: Hallo';
        $mail->fromAddress = $sender;
        $list = new ListConfig('mylist', 'mylist@example.org', $rawConfig, new InlineMemberResolver(['m@example.org'], ['o@example.org']));
        return $filter->filter($mail, $list, 'raw', []);
    }

    public function testReplyTokenRejectedForNonMember(): void
    {
        $result = $this->runReply(['reply-to' => 'masked-sender'], 'outsider@example.com');
        $this->assertSame('reject.reply_not_allowed', $result->reason);
    }

    public function testReplyTokenOnNonMaskedListIsRejected(): void
    {
        $result = $this->runReply(['reply-to' => 'list'], 'm@example.org');
        $this->assertSame('reject.reply_not_enabled', $result->reason);
    }

    public function testReplyTokenWithUnresolvableTargetIsRejected(): void
    {
        $result = $this->runReply(['reply-to' => 'masked-sender'], 'm@example.org', false);
        $this->assertSame('reject.reply_target_unknown', $result->reason);
    }

    public function testMaskedSenderIgnoresPostAccessMembers(): void
    {
        $result = $this->runReply(['reply-to' => 'masked-sender', 'post-access-members' => 'moderate'], 'm@example.org');
        $this->assertTrue($result->isDistribute);
        $result = $this->runReply(['reply-to' => 'masked-sender', 'post-access-members' => 'deny'], 'm@example.org');
        $this->assertTrue($result->isDistribute);
    }

    public function testMaskedBothHonoursPostAccessMembers(): void
    {
        $result = $this->runReply(['reply-to' => 'masked-both', 'post-access-members' => 'deny'], 'm@example.org');
        $this->assertSame('reject.members_denied', $result->reason);
        $result = $this->runReply(['reply-to' => 'masked-both', 'post-access-members' => 'moderate'], 'm@example.org');
        $this->assertTrue($result->isModeration);
    }

    public function testReplyRelayAlsoWorksOnSenderAndBothLists(): void
    {
        // Used by the archive's "reply to the author" button — a private message, never moderated.
        foreach (['sender', 'both'] as $mode) {
            $result = $this->runReply(['reply-to' => $mode, 'post-access-members' => 'moderate'], 'm@example.org');
            $this->assertTrue($result->isDistribute, $mode);
        }
        $this->assertSame('reject.reply_not_enabled', $this->runReply(['reply-to' => 'nobody'], 'm@example.org')->reason);
    }

    private function runThreadReply(?array $resolved, ?string $token = 'tok'): \Hengeb\Listig\Mail\FilterResult
    {
        $threads = $this->createStub(ReplyThreadStore::class);
        $threads->method('extractToken')->willReturn($token);
        $threads->method('resolve')->willReturn($resolved);
        $filter = new IncomingMailFilter(
            $this->createStub(RateLimiter::class),
            new HeaderFilter(),
            new SpamFilter([], new Logger(LogLevel::Error)),
            $this->createStub(ReplyTargetStore::class),
            $threads,
            new SenderAuthenticator(new HeaderFilter(), new OrganizationalDomain()),
        );
        $mail = new IncomingMail();
        $mail->headersRaw = "To: mylist+re-tok@example.org\r\n";
        $mail->autoSubmitted = '';
        $mail->subject = 'Re: Hallo';
        $mail->fromAddress = 'm@example.org';
        $list = new ListConfig('mylist', 'mylist@example.org', [], new InlineMemberResolver(['m@example.org'], ['o@example.org']));
        return $filter->filter($mail, $list, 'raw', []);
    }

    public function testThreadReplyToAnExistingArchivedMailIsDistributed(): void
    {
        $this->assertTrue($this->runThreadReply(['message_id' => 'a@x', 'thread_root' => 'a@x'])->isDistribute);
    }

    public function testThreadReplyWithUnknownTargetIsRejectedWithAHint(): void
    {
        $this->assertSame('reject.reply_thread_unknown', $this->runThreadReply(null)->reason);
    }

    public function testMailWithoutThreadTagIsNotAffected(): void
    {
        $this->assertTrue($this->runThreadReply(null, null)->isDistribute);
    }

    private function runUnverified(string $mode, string $sender, string $headersRaw = '', array $extra = []): \Hengeb\Listig\Mail\FilterResult
    {
        $mail = new IncomingMail();
        $mail->headersRaw = $headersRaw;
        $mail->autoSubmitted = '';
        $mail->subject = 'Hi';
        $mail->fromAddress = $sender;
        $list = new ListConfig(
            'mylist',
            'mylist@example.org',
            ['post-access-unauthenticated' => $mode] + $extra,
            new InlineMemberResolver(['m@example.org'], ['o@example.org']),
        );
        return $this->filter()->filter($mail, $list, 'raw', []);
    }

    private const AUTHENTICATED = "Authentication-Results: mx.example.org; dmarc=pass header.from=example.org\r\n";

    public function testUnauthenticatedAllowDistributesUnverifiedMail(): void
    {
        $this->assertTrue($this->runUnverified('allow', 'm@example.org')->isDistribute);
    }

    public function testUnauthenticatedModerateHoldsUnverifiedMail(): void
    {
        $this->assertTrue($this->runUnverified('moderate', 'm@example.org')->isModeration);
    }

    public function testUnauthenticatedModerateLetsVerifiedMailThrough(): void
    {
        $this->assertTrue($this->runUnverified('moderate', 'm@example.org', self::AUTHENTICATED)->isDistribute);
    }

    public function testUnauthenticatedDenyRejectsUnverifiedMailOnly(): void
    {
        $r = $this->runUnverified('deny', 'm@example.org');
        $this->assertTrue($r->isReject);
        $this->assertSame('reject.unauthenticated', $r->reason);
        $this->assertTrue($this->runUnverified('deny', 'm@example.org', self::AUTHENTICATED)->isDistribute);
    }

    public function testUnauthenticatedAppliesToOwnersAndSendersToo(): void
    {
        $this->assertTrue($this->runUnverified('moderate', 'o@example.org')->isModeration, 'owner');
        $this->assertTrue($this->runUnverified('deny', 'o@example.org')->isReject, 'owner');
        $this->assertTrue($this->runUnverified('deny', 's@example.org', '', ['senders' => ['s@example.org']])->isReject, 'senders:');
    }

    public function testUnauthenticatedModerateRefusesPrivateReplyRelayInsteadOfHolding(): void
    {
        $store = $this->createStub(ReplyTargetStore::class);
        $store->method('extractToken')->willReturn('tok');
        $store->method('resolve')->willReturn(new ReplyTarget(new Member('t@example.org'), true));
        $filter = new IncomingMailFilter(
            $this->createStub(RateLimiter::class),
            new HeaderFilter(),
            new SpamFilter([], new Logger(LogLevel::Error)),
            $store,
            $this->createStub(ReplyThreadStore::class),
            new SenderAuthenticator(new HeaderFilter(), new OrganizationalDomain()),
        );
        $mail = new IncomingMail();
        $mail->headersRaw = "To: mylist+r-tok@example.org\r\n";
        $mail->autoSubmitted = '';
        $mail->subject = 'Re: Hallo';
        $mail->fromAddress = 'm@example.org';
        $list = new ListConfig(
            'mylist',
            'mylist@example.org',
            ['reply-to' => 'masked-sender', 'post-access-unauthenticated' => 'moderate'],
            new InlineMemberResolver(['m@example.org'], ['o@example.org']),
        );
        $r = $filter->filter($mail, $list, 'raw', []);
        $this->assertTrue($r->isReject);
        $this->assertSame('reject.unauthenticated', $r->reason);
    }

    /** ListConfig::canPost() drives the "write to the list" / "reply" buttons — it must agree with the real gate. */
    public function testCanPostAgreesWithThePostAccessFilter(): void
    {
        $restrictions = new \Hengeb\Listig\Config\RestrictionList([['mail' => 'banned@example.org']]);
        $senders = ['o@example.org', 'm@example.org', 'x@example.com', 's@example.org', 'banned@example.org'];
        foreach (['allow', 'deny', 'moderate'] as $members) {
            foreach (['allow', 'deny', 'moderate'] as $public) {
                $list = new ListConfig(
                    'mylist',
                    'mylist@example.org',
                    ['post-access-members' => $members, 'post-access-public' => $public, 'senders' => ['s@example.org']],
                    new InlineMemberResolver(['m@example.org', 'banned@example.org'], ['o@example.org']),
                    restrictions: $restrictions,
                );
                foreach ($senders as $sender) {
                    $mail = new IncomingMail();
                    $mail->headersRaw = '';
                    $mail->autoSubmitted = '';
                    $mail->subject = 'Hi';
                    $mail->fromAddress = $sender;
                    $result = $this->filter()->filter($mail, $list, 'raw', []);
                    $this->assertSame(
                        $result->isDistribute || $result->isModeration,
                        $list->canPost($sender),
                        "members=$members public=$public sender=$sender",
                    );
                }
            }
        }
    }
}
