<?php

declare(strict_types=1);

namespace Hengeb\Listig\Mail;

use Hengeb\Listig\Config\ListConfig;
use Hengeb\Listig\Smtp\SmtpConnectionFactory;
use Symfony\Component\Mailer\Mailer;
use Symfony\Component\Mime\Address;
use Symfony\Component\Mime\Email;
use Symfony\Component\Mime\Part\DataPart;

/**
 * Sends short plain-text operational notifications (delivery failures, bounces,
 * moderation/unsubscribe notices) from a list's address. Shared "build Email, get
 * transport, send, log on failure" helper used by QueueSender, UnsubscribeController,
 * ModerationResponseHandler, and bin/worker.php.
 *
 * Every notification sent through here uses a null-sender envelope
 * (`MAIL FROM:<>`, see NullSenderEnvelope) and carries `X-Listig-Auto`/
 * `Auto-Submitted` headers — both exist specifically to break the bounce loop
 * documented on BounceHandler::isBounceOnOwnNotification(): a notification is
 * itself a bounce-forwarding target (BounceHandler::forwardToOwners() calls
 * sendToOwners()), so if a notification is itself undeliverable, it must
 * never be able to trigger another bounce that loops back through here again.
 */
class NotificationMailer
{
    /** Marks a mail as generated by this class — never a member/owner's own content. See the class docblock. */
    public const string AUTO_HEADER = 'X-Listig-Auto';

    public function __construct(
        private readonly SmtpConnectionFactory $smtpFactory,
    ) {
    }

    /** @param Address[]|string[] $to */
    public function send(
        ListConfig $list,
        array|string $to,
        string $subject,
        string $text,
        ?string $attachmentContent = null,
        ?string $attachmentName = null,
        ?string $attachmentMimeType = null,
    ): void {
        $recipients = is_array($to) ? $to : [$to];
        if (empty($recipients)) {
            return;
        }

        try {
            $transport = $this->smtpFactory->getTransport($list);
            $mailer = new Mailer($transport);

            $addressRecipients = array_map(
                fn($recipient) => $recipient instanceof Address ? $recipient : new Address($recipient),
                $recipients,
            );

            $email = new Email();
            $email->from(new Address($list->mail, $list->displayName));
            $email->to(...$addressRecipients);
            $email->subject($subject);
            $email->text($text);

            // See the class docblock — every notification is auto-generated and
            // must never itself be able to trigger a bounce that loops back
            // through BounceHandler.
            $email->getHeaders()->addTextHeader(self::AUTO_HEADER, 'notification');
            $email->getHeaders()->addTextHeader('Auto-Submitted', 'auto-generated');

            if ($attachmentContent !== null) {
                // message/rfc822 per RFC 2046 only allows 7bit/8bit/binary transfer
                // encoding, never quoted-printable/base64 — Email::attach() has no
                // encoding parameter and DataPart defaults to base64 for a null
                // charset, which made mail clients refuse to display the attached
                // original mail at all (see ModerationMailer for the same fix).
                if ($attachmentMimeType === 'message/rfc822') {
                    $email->addPart(new DataPart($attachmentContent, $attachmentName, $attachmentMimeType, '8bit'));
                } else {
                    $email->attach($attachmentContent, $attachmentName, $attachmentMimeType);
                }
            }

            $mailer->send($email, new NullSenderEnvelope($addressRecipients));
        } catch (\Throwable $e) {
            error_log("Listig: Failed to send notification '{$subject}' for list {$list->name}: " . $e->getMessage());
        }
    }

    public function sendToOwners(
        ListConfig $list,
        string $subject,
        string $text,
        ?string $attachmentContent = null,
        ?string $attachmentName = null,
        ?string $attachmentMimeType = null,
    ): void {
        $owners = $list->getOwners();
        if (empty($owners)) {
            return;
        }

        $this->send(
            $list,
            array_map(fn($owner) => new Address($owner->email), $owners),
            $subject,
            $text,
            $attachmentContent,
            $attachmentName,
            $attachmentMimeType,
        );
    }
}
